module.exports = {
  title: '自动部署项目',
  selectConfig: '选择部署的配置：',
  notExist: '不存在！',
  addConfigJson: '请先在项目根目录新建"zr-deploy-config.json"，内容如下：',
  configIncorrect: '配置不正确！',
  needKeys: '需要的字段：',
  buildSuccess: '打包完成！',
  buildFailed: '打包失败！',
  compressing: '正在压缩',
  compressSuccess: '压缩完成！',
  compressFailed: '压缩失败！',
  buildDist: '打包路径',
  connectingServer: '正在连接服务器',
  connectedServer: '服务器连接成功！',
  connectServerFailed: '服务器连接失败！',
  distDirRule: '需为绝对路径，且不能为根目录"/"',
  deploying: '正在部署项目',
  deploySuccess: '部署完成！',
  deployFailed: '部署失败！',
  projectPath: '项目路径：',
};
